CFLAGS= -Wall -lrt -lpthread
BIN = bin
INC = include
LIB = lib
OBJ = obj
SRC = src

p1: p1.c
	gcc -o bin/p1 $^	$(CFLAGS) 
	bin/p1

p2: p2.c
	gcc -o bin/p2 $^	$(CFLAGS) 
	bin/p2

p3: p3.c
	gcc -o bin/p3 $^	$(CFLAGS) 
	bin/p3

p4: p4.c
	gcc -o bin/p4 $^	$(CFLAGS) 
	bin/p4

clean:
	rm -rf bin/*

remove:
